### ISSUE TITLE
Error message when I try to run you code with your dataser

### ISSUE THREAD

**Issue by wpmarinho** [mmkhajah/dkt#1]
Hi

My name is Wemerson and I'm trying to replicate your results.

When I start your code with your dataset I receive the following error:

What I´m doing wrong? ( I already tried to remove all ocorrences of only one question, but it doesn't work)

Thank You

Training Sequences: 3361
Testing Sequences: 856
Number of skills: 124
C:\toolkits\Anaconda2-4.2.0\lib\site-packages\keras-1.1.0-py2.7.egg\keras\layers\core.py:1112: UserWarning: TimeDistributedDense is deprecated, please use TimeDistributed(Dense(...)) instead.
  warnings.warn('TimeDistributedDense is deprecated, '
C:\toolkits\Anaconda2-4.2.0\lib\site-packages\keras-1.1.0-py2.7.egg\keras\models.py:540: UserWarning: "class_mode" argument is deprecated, please remove it.
  warnings.warn('"class_mode" argument is deprecated, '
Traceback (most recent call last):
  File "dkt.py", line 303, in <module>
    main()
  File "dkt.py", line 140, in main
    run_func(training_seqs, num_skills, trainer, batch_size, time_window, finished_batch)
  File "dkt.py", line 230, in run_func
    f(X[:,t:(t+time_window),:], Y[:,t:(t+time_window),:])
  File "dkt.py", line 108, in trainer
    overall_loss[0] += model.train_on_batch(X, Y)[0]
IndexError: too many indices for array

**Comment by singh-alok** [comment]
you have to change line 
from 
      overall_loss[0] += model.train_on_batch(X, Y)[0]
to 
      overall_loss[0] += model.train_on_batch(X, Y)

this could happen because of version change.

**Comment by wpmarinho** [comment]
Thank You... I had already realized that! ;)
